import { createConnection } from "mysql2/promise";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("DATABASE_URL not set");
  process.exit(1);
}

const connection = await createConnection(DATABASE_URL);

const sampleCompanies = [
  {
    name: "Nextera Robotics",
    ticker: "NXTR",
    exchange: "NASDAQ",
    status: "upcoming",
    industry: "Robotics & Automation",
    sector: "Technology",
    description: "Nextera Robotics develops autonomous robotic systems for warehouse logistics and last-mile delivery. The company's AI-powered robots can navigate complex environments and handle packages of varying sizes.",
    headquarters: "Austin, TX",
    founded: "2019",
    ceo: "Sarah Chen",
    employees: "450",
    website: "https://nexterarobotics.example.com",
    priceLow: "18.00",
    priceHigh: "22.00",
    priceActual: null,
    sharesOffered: 15000000,
    offeringSize: 300000000,
    marketCap: 1800000000,
    expectedDate: "2026-05-15 00:00:00",
    pricedDate: null,
    revenue: 85000000,
    netIncome: -12000000,
    fiscalYear: "2025",
    leadUnderwriter: "Goldman Sachs, Morgan Stanley",
    slug: "nextera-robotics",
  },
  {
    name: "CloudVault Security",
    ticker: "CVLT",
    exchange: "NYSE",
    status: "upcoming",
    industry: "Cybersecurity",
    sector: "Technology",
    description: "CloudVault Security provides enterprise-grade zero-trust security solutions for cloud-native applications. Their platform protects over 500 enterprise customers across financial services, healthcare, and government sectors.",
    headquarters: "San Francisco, CA",
    founded: "2018",
    ceo: "Marcus Rivera",
    employees: "820",
    website: "https://cloudvault.example.com",
    priceLow: "24.00",
    priceHigh: "28.00",
    priceActual: null,
    sharesOffered: 20000000,
    offeringSize: 520000000,
    marketCap: 3200000000,
    expectedDate: "2026-05-22 00:00:00",
    pricedDate: null,
    revenue: 210000000,
    netIncome: 15000000,
    fiscalYear: "2025",
    leadUnderwriter: "J.P. Morgan, Barclays",
    slug: "cloudvault-security",
  },
  {
    name: "GreenGrid Energy",
    ticker: "GGEN",
    exchange: "NASDAQ",
    status: "priced",
    industry: "Renewable Energy",
    sector: "Energy",
    description: "GreenGrid Energy operates a network of smart microgrids combining solar, wind, and battery storage for commercial and industrial customers. The company has deployed over 200 microgrids across 15 states.",
    headquarters: "Denver, CO",
    founded: "2017",
    ceo: "David Park",
    employees: "1200",
    website: "https://greengrid.example.com",
    priceLow: "30.00",
    priceHigh: "34.00",
    priceActual: "32.00",
    sharesOffered: 25000000,
    offeringSize: 800000000,
    marketCap: 4500000000,
    expectedDate: null,
    pricedDate: "2026-04-10 00:00:00",
    revenue: 380000000,
    netIncome: 28000000,
    fiscalYear: "2025",
    leadUnderwriter: "Morgan Stanley, Credit Suisse",
    slug: "greengrid-energy",
  },
  {
    name: "MedGenome AI",
    ticker: "MGAI",
    exchange: "NASDAQ",
    status: "trading",
    industry: "Biotechnology",
    sector: "Healthcare",
    description: "MedGenome AI uses artificial intelligence and machine learning to accelerate drug discovery and genomic analysis. Their platform has identified over 30 novel drug candidates, with 3 currently in clinical trials.",
    headquarters: "Cambridge, MA",
    founded: "2016",
    ceo: "Dr. Elena Vasquez",
    employees: "650",
    website: "https://medgenome.example.com",
    priceLow: "36.00",
    priceHigh: "40.00",
    priceActual: "38.50",
    sharesOffered: 18000000,
    offeringSize: 693000000,
    marketCap: 5200000000,
    expectedDate: null,
    pricedDate: "2026-03-20 00:00:00",
    revenue: 145000000,
    netIncome: -45000000,
    fiscalYear: "2025",
    leadUnderwriter: "Goldman Sachs, Jefferies",
    slug: "medgenome-ai",
  },
  {
    name: "UrbanFleet Mobility",
    ticker: "UFLM",
    exchange: "NYSE",
    status: "upcoming",
    industry: "Transportation",
    sector: "Industrials",
    description: "UrbanFleet Mobility operates an electric vehicle fleet management platform for urban delivery and ride-sharing services. The company manages over 15,000 EVs across 30 major metropolitan areas.",
    headquarters: "Chicago, IL",
    founded: "2020",
    ceo: "James Okonkwo",
    employees: "380",
    website: "https://urbanfleet.example.com",
    priceLow: "14.00",
    priceHigh: "17.00",
    priceActual: null,
    sharesOffered: 22000000,
    offeringSize: 341000000,
    marketCap: 1400000000,
    expectedDate: "2026-06-05 00:00:00",
    pricedDate: null,
    revenue: 120000000,
    netIncome: -30000000,
    fiscalYear: "2025",
    leadUnderwriter: "Citigroup, Deutsche Bank",
    slug: "urbanfleet-mobility",
  },
  {
    name: "Paloma Fintech",
    ticker: "PLMA",
    exchange: "NYSE",
    status: "priced",
    industry: "Financial Technology",
    sector: "Financials",
    description: "Paloma Fintech provides embedded banking and payment infrastructure for SaaS platforms. Their API-first approach enables any software company to offer financial services to their customers.",
    headquarters: "New York, NY",
    founded: "2018",
    ceo: "Ana Gutierrez",
    employees: "550",
    website: "https://paloma.example.com",
    priceLow: "26.00",
    priceHigh: "30.00",
    priceActual: "28.50",
    sharesOffered: 16000000,
    offeringSize: 456000000,
    marketCap: 2800000000,
    expectedDate: null,
    pricedDate: "2026-04-05 00:00:00",
    revenue: 175000000,
    netIncome: 22000000,
    fiscalYear: "2025",
    leadUnderwriter: "J.P. Morgan, Goldman Sachs",
    slug: "paloma-fintech",
  },
];

try {
  for (const c of sampleCompanies) {
    await connection.execute(
      `INSERT INTO companies (name, ticker, exchange, status, industry, sector, description, headquarters, founded, ceo, employees, website, priceLow, priceHigh, priceActual, sharesOffered, offeringSize, marketCap, expectedDate, pricedDate, revenue, netIncome, fiscalYear, leadUnderwriter, slug) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE name=VALUES(name)`,
      [
        c.name, c.ticker, c.exchange, c.status,
        c.industry, c.sector, c.description, c.headquarters,
        c.founded, c.ceo, c.employees, c.website,
        c.priceLow, c.priceHigh, c.priceActual,
        c.sharesOffered, c.offeringSize, c.marketCap,
        c.expectedDate, c.pricedDate,
        c.revenue, c.netIncome, c.fiscalYear,
        c.leadUnderwriter, c.slug,
      ]
    );
    console.log(`✓ Inserted: ${c.name}`);
  }
  console.log("\n✅ Seed completed successfully!");
} catch (error) {
  console.error("Seed failed:", error);
  process.exit(1);
} finally {
  await connection.end();
}
